_wandb:
    value:
        cli_version: 0.18.7
        m:
            - "1": epoch/val_accuracy
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/epoch
              "6":
                - 3
              "7": []
            - "1": epoch/val_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/learning_rate
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/accuracy
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.12.6
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
            "3":
                - 2
                - 3
                - 7
                - 8
                - 16
                - 23
                - 38
                - 55
            "4": 3.12.6
            "5": 0.18.7
            "8":
                - 1
                - 3
                - 5
            "10":
                - 9
                - 17
            "12": 0.18.7
            "13": windows-amd64
batch_size:
    value: 32
epochs:
    value: 50
learning_rate:
    value: 0.0001
